development: &common_settings
    cluster_name: 'Terra'
    dashboard_url: '/pun/dev/OOD-Dashboard'
    file_app_url: '/pun/sys/files/fs'
    file_editor_url: '/pun/sys/file-editor/edit'
    home_page: 'https://hprc.tamu.edu'
    request_email: 'hsuk1001@tamu.edu'
    help_email: 'hsuk1001@tamu.edu'
    modules_db_path: '/sw/hprc/sw/portal_utils/modules.sqlite3'
    driver_scripts_path: '/var/www/ood/apps/dev/hsuk1001/gateway/OOD-Dashboard/machine_driver_scripts'
    tamubatch_path: '/sw/local/bin/tamubatch'
    send_result_path: '/var/www/ood/apps/dev/hsuk1001/gateway/OOD-Dashboard/machine_driver_scripts/send_result.sh'
    
production:
    <<: *common_settings
    dashboard_url: '/pun/sys/OOD-Dashboard'
    request_email: 'help@hprc.tamu.edu'
    driver_scripts_path: '/var/www/ood/apps/sys/OOD-Dashboard/machine_driver_scripts'

